apps/option/urls.py
from django.conf.urls import patterns, url

from .views import OptionDetailView

urlpatterns = patterns('',
                       url(r"^(?P<pk>[0-9]+)/$", OptionDetailView.as_view(), name="detail"),
                        )

apps/products/urls.py
from django.conf.urls import url, include, patterns
from .views import ProductSearch
from saleor.product import views

urlpatterns = patterns('',
                       url(r'^$', ProductSearch.as_view(), name='search'),
                       url(r'^(?P<product_id>[0-9]+)/variations/$',
                           'apps.products.views.product_variants_list', name='variations'),
                       url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
                           views.product_details, name='details'),
                       url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
                           views.category_index, name='category')
)

saleor/dashboard/option/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    # url(r'^$',
    #     views.product_list, name='product-list'),
    # url(r'^(?P<pk>[0-9]+)/update/$',
    #     views.product_edit, name='product-update'),
    # url(r'^add/$',
    #     views.product_create, name='product-add'),
    # url(r'^(?P<pk>[0-9]+)/delete/$',
    #     views.product_delete, name='product-delete'),
    #
    # url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
    #     views.variant_edit, name='variant-update'),
    # url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
    #     views.variant_edit, name='variant-add'),
    # url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
    #     views.variant_delete, name='variant-delete'),
    # url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
    #     views.variants_bulk_delete, name='variant-bulk-delete'),
    #
    # url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
    #     views.stock_edit, name='product-stock-update'),
    # url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
    #     views.stock_edit, name='product-stock-add'),
    # url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
    #     views.stock_delete, name='product-stock-delete'),
    # url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
    #     views.stock_bulk_delete, name='stock-bulk-delete'),
    #
    # url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
    #     views.product_image_edit, name='product-image-update'),
    # url(r'^(?P<product_pk>[0-9]+)/images/add/$',
    #     views.product_image_edit, name='product-image-add'),
    # url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
    #     views.product_image_delete, name='product-image-delete'),
    # url('^(?P<product_pk>[0-9]+)/images/reorder/$',
    #     api.reorder_product_images, name='product-images-reorder'),
    # url('^(?P<product_pk>[0-9]+)/images/upload/$',
    #     api.upload_image, name='product-images-upload'),

    url(r'options/$',
        views.option_list, name='product-options'),
    url(r'options/(?P<pk>[0-9]+)/$',
        views.option_edit, name='product-option-update'),
    url(r'options/add/$',
        views.option_edit, name='product-option-add'),
    url(r'options/(?P<pk>[0-9]+)/delete/$',
        views.option_delete, name='product-option-delete'),
]

saleor/dashboard/product/urls.py
from django.conf.urls import url

from . import api
from . import views


urlpatterns = [
    url(r'^$',
        views.product_list, name='product-list'),
    url(r'^(?P<pk>[0-9]+)/update/$',
        views.product_edit, name='product-update'),
    url(r'^add/$',
        views.product_create, name='product-add'),
    url(r'^(?P<pk>[0-9]+)/delete/$',
        views.product_delete, name='product-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$',
        views.variant_edit, name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$',
        views.variant_edit, name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$',
        views.variant_delete, name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/',
        views.variants_bulk_delete, name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$',
        views.stock_edit, name='product-stock-update'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$',
        views.stock_edit, name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$',
        views.stock_delete, name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/',
        views.stock_bulk_delete, name='stock-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$',
        views.product_image_edit, name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$',
        views.product_image_edit, name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$',
        views.product_image_delete, name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$',
        api.reorder_product_images, name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$',
        api.upload_image, name='product-images-upload'),

    url(r'attributes/$',
        views.attribute_list, name='product-attributes'),
    url(r'attributes/(?P<pk>[0-9]+)/$',
        views.attribute_edit, name='product-attribute-update'),
    url(r'attributes/add/$',
        views.attribute_edit, name='product-attribute-add'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$',
        views.attribute_delete, name='product-attribute-delete'),
    url(r'iostock/$',
        views.input_output_stock, name='product-iostock'),
    url(r'options/$',
        views.optionset_list, name='product-options-set'),
    url(r'options/(?P<pk>[0-9]+)/$',
        views.ProductOptionDetail.as_view(), name='product-option-set-detail'),
    url(r'options/(?P<pk>[0-9]+)/edit/$',
        views.optionset_form, name='product-option-set-edit'),
    url(r'options/add/$',
        views.optionset_form, name='product-option-set-add'),
    url(r'options/(?P<pk>[0-9]+)/delete/$',
        views.optionset_delete, name='product-option-set-delete'),

    url(r'options/(?P<pk_parent>[0-9]+)/(?P<pk>[0-9]+)/$',
        views.option_form, name='option-set-option-edit'),
    url(r'options/(?P<pk_parent>[0-9]+)/(?P<pk>[0-9]+)/delete/$',
        views.option_delete, name='option-set-option-delete'),
    url(r'options/(?P<pk_parent>[0-9]+)/add/$',
        views.option_form, name='option-set-option-add'),
]

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category')
]

saleor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib.sitemaps.views import sitemap


from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .userprofile.urls import urlpatterns as userprofile_urls
from .dashboard.urls import urlpatterns as dashboard_urls

from .core.views import home


urlpatterns = [
    url(r'^account/', include(registration_urls, namespace='registration')),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^selectable/', include('selectable.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'', include('payments.urls'))
]

saleor/product/models/fields.py
from django.db import models

from .. import forms


class WeightField(models.DecimalField):

    description = 'A field which stores a weight.'

    def __init__(self, verbose_name=None, unit=None, *args, **kwargs):
        self.unit = unit
        super(WeightField, self).__init__(verbose_name, *args, **kwargs)

    def deconstruct(self):
        name, path, args, kwargs = super(WeightField, self).deconstruct()
        kwargs['unit'] = self.unit
        return name, path, args, kwargs

    def formfield(self, **kwargs):
        defaults = {'unit': self.unit,
                    'decimal_places': self.decimal_places,
                    'form_class': forms.WeightField}
        defaults.update(kwargs)
        return super(WeightField, self).formfield(**defaults)

apps/option/views.py
from django.shortcuts import render

from django.views.generic import DetailView
from .models import Option


class OptionDetailView(DetailView):
    model = Option
    template_name = 'option/detail.html'
    queryset = Option.objects.all()

apps/products/views.py
from django.views.generic import ListView
from saleor.product.models import Product, Category, ProductVariant
from django.db.models import Q
from .serializers import ProductSerializer, ProductVariantSerializer, ProductVariantSerializer1
from rest_framework import viewsets

from django.contrib import messages

from django.core.cache import cache
from django.utils.cache import get_cache_key
from django.http.response import JsonResponse


class ProductSearch(ListView):
    model = Product
    queryset = Product.objects.all()
    context_object_name = 'products'
    template_name = 'product/search.html'
    paginate_by = 6

    def get_queryset(self):
        return self.get_cache_queryset()

    def get_cache_queryset(self):


        key = str(get_cache_key(self.request))
        query = cache.get(key)

        if query is None:
            query = self.queryset
            if self.request.GET.get('q'):
                query = query.filter(name__contains=self.request.GET.get('q'))

            if self.request.GET.get('category'):
                try:
                    cat = Category.objects.get(slug=self.request.GET.get('category'))
                    query= query.filter(Q(categories__slug=self.request.GET.get('category')) | Q(categories__in=cat.children.all()))
                except Category.DoesNotExist:
                    messages.add_message(self.request, messages.WARNING, 'Warning!! error with category %s' %(self.request.GET.get('category')))

            if self.request.GET.get('min_price') and self.request.GET.get('max_price'):
                query = query.filter(Q(price__gte = self.request.GET.get('min_price')) & Q(price__lte= self.request.GET.get('max_price')))

            if self.request.GET.get('order_by'):
                query = query.order_by(self.request.GET.get('order_by'))

            query = query.prefetch_related('images', 'variants', 'variants__stock')

            cache.set(key, query, 86400)

        return query

    def get_context_data(self, **kwargs):
        context = super(ProductSearch, self).get_context_data(**kwargs)
        context['min_price_param'] = self.request.GET.get('min_price', 0)
        context['max_price_param'] = self.request.GET.get('max_price', 10000)
        context['order_by_param'] = self.request.GET.get('order_by', 'Position')

        context['style_product'] = self.request.GET.get('style', 'column')

        # TODO: Quiet this line and create dynamic widget
        context['featured_products'] = Product.objects.filter(outstanding=True).prefetch_related('images')[:8]

        context['text_search'] = self.request.GET.get('q', '')
        try:
            context['category_selected'] = Category.objects.get(slug=self.request.GET.get('category', ''))
        except:
            context['category_selected'] = {}
        context['categories'] = Category.objects.filter(hidden=False, parent=None)
        return context

class ProductViewSet(viewsets.ModelViewSet):
    """
    A simple ViewSet for viewing Products
    """
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

class ProductVariantSet(viewsets.ModelViewSet):
    """"
    A simple ViewSet for viewwing Variants
    """
    queryset = ProductVariant.objects.all()
    serializer_class = ProductVariantSerializer


def product_variants_list(request, **kwargs):
    """
        Get JSON LIST to variants products
    """
    if kwargs.get('product_id'):
            variants = ProductVariant.objects.filter(product=kwargs['product_id'])
    else:
        variants = []

    return JsonResponse(ProductVariantSerializer1(variants, many=True).data, safe=False)

saleor/dashboard/category/views.py
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from ...product.models import Category
from ..views import staff_member_required
from .forms import CategoryForm


@staff_member_required
def category_list(request, root_pk=None):
    root = None
    path = None
    categories = Category.tree.root_nodes()
    if root_pk:
        root = get_object_or_404(Category, pk=root_pk)
        path = root.get_ancestors(include_self=True) if root else []
        categories = root.get_children()
    ctx = {'categories': categories, 'path': path, 'root': root}
    return TemplateResponse(request, 'dashboard/category/list.html', ctx)


@staff_member_required
def category_create(request, root_pk=None):
    category = Category()
    form = CategoryForm(request.POST or None, parent_pk=root_pk)
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    ctx = {'category': category, 'form': form}
    return TemplateResponse(request, 'dashboard/category/detail.html', ctx)


@staff_member_required
def category_edit(request, root_pk=None):
    category = get_object_or_404(Category, pk=root_pk)
    form = CategoryForm(request.POST or None, instance=category,
                        parent_pk=category.parent_id)
    status = 200
    if form.is_valid():
        category = form.save()
        messages.success(request, _('Added category %s') % category)
        if root_pk:
            return redirect('dashboard:category-list', root_pk=root_pk)
        else:
            return redirect('dashboard:category-list')
    elif form.errors:
        status = 400
    ctx = {'category': category, 'form': form, 'status': status}
    template = 'dashboard/category/modal_edit.html'
    return TemplateResponse(request, template, ctx, status=status)


@staff_member_required
def category_delete(request, pk):
    category = get_object_or_404(Category, pk=pk)
    if request.method == 'POST':
        category.delete()
        messages.success(request, _('Deleted category %s') % category)
        root_pk = None
        if category.parent:
            root_pk = category.parent.pk
        # if root_pk:
        #     return redirect('dashboard:category-list', root_pk=root_pk)
        # else:
        #     return redirect('dashboard:category-list')
        return redirect('dashboard:category-list')
    ctx = {'category': category,
           'descendants': list(category.get_descendants()),
           'products_count': len(category.products.all())}
    return TemplateResponse(request,
                            'dashboard/category/modal_category_confirm_delete.html',
                            ctx)

saleor/dashboard/customer/views.py
from __future__ import unicode_literals

from django.db.models import Count, Max
from django.shortcuts import get_object_or_404
from django.template.response import TemplateResponse
from django.utils.translation import ugettext_lazy as _

from .forms import CustomerSearchForm
from ..utils import paginate
from ..views import staff_member_required
from ...userprofile.models import User


@staff_member_required
def customer_list(request):
    customers = (
        User.objects
        .prefetch_related('orders', 'addresses')
        .select_related('default_billing_address', 'default_shipping_address')
        .annotate(
            num_orders=Count('orders', distinct=True),
            last_order=Max('orders', distinct=True)))

    form = CustomerSearchForm(request.GET or None, queryset=customers)
    form_values = [(field.name, field.value() or '') for field in form]
    if form.is_valid():
        customers = form.search()
    else:
        customers = customers.filter(
            orders__status__in=['new', 'payment-pending', 'fully-paid'])
    title = _('Results (%s)') % len(customers)

    customers, paginator = paginate(customers, 30, request.GET.get('page'))
    ctx = {'customers': customers, 'form': form, 'title': title,
           'paginator': paginator, 'default_pagination_params': form_values}
    return TemplateResponse(request, 'dashboard/customer/list.html', ctx)


@staff_member_required
def customer_details(request, pk):
    queryset = User.objects.prefetch_related(
        'orders', 'addresses').select_related('default_billing_address')
    customer = get_object_or_404(queryset, pk=pk)
    customer_orders = customer.orders.all()
    ctx = {'customer': customer, 'customer_orders': customer_orders}
    return TemplateResponse(request, 'dashboard/customer/detail.html', ctx)

saleor/dashboard/templates/dashboard/product/option/confirm_delete.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}{% trans "Delete attribute" %} - {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-attributes' %}">{% trans "Attributes" %}</a></li>
        <li><i class="mdi-navigation-chevron-right"></i> {% trans "Delete attribute" %}</li>
    </ul>
{% endblock %}

{% block content %}
    <p>{% trans "Are you sure you want to delete the following attribute?" %}</p>
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <ul class="collection">
                <li class="collection-item">
                    {{ attribute }}
                </li>
            </ul>
        </div>

        <div class="row">
            <div class="col m6 l4 offset-m3 offset-l4 right-align">
                <a href="{% url 'dashboard:product-attributes' %}" class="btn-flat"><i class="mdi-content-clear"></i> {% trans "Cancel" %}</a>
                <button type="submit" class="btn materialize-red"><i class="mdi-action-delete"></i> {% trans "Delete" %}</button>
            </div>
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/product/option/form.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load static %}

{% block title %}{% if option.pk %}{{ attribute }}{% else %}{% trans 'Add new option' %}{% endif %} - {% trans "Options" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-options{% endblock %}

{% block header_menu %}
    {% url "dashboard:product-options" as url %}
    {% include "dashboard/includes/_back-link.html" with url=url %}
{% endblock %}

{% block header_extra %}
    {% if option.pk %}
        <a class="dropdown-button" href="#" data-activates="option-delete" data-constrainwidth="false">
            <i class="mdi-navigation-more-vert"></i>
        </a>
        <ul id="option-delete" class="dropdown-content">
            <li>
                <a class="modal-trigger-custom" href="#base-modal"
                   data-href="{% url 'dashboard:product-option-delete' pk=option.pk %}">
                    {% trans "Remove option" %}
                </a>
            </li>
        </ul>
    {% endif %}
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs breadcrumbs--with-menu">
        <li><a href="{% url 'dashboard:product-options' %}">{% trans "Options" %}</a></li>
        <li>{% if option.pk %}{{ option }}{% else %}{% trans 'Add new option' %}{% endif %}</li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <form method="post" enctype="multipart/form-data" id="form-options">
        <div class="row">
            <div class="col l8">
                <div class="row">
                    {% csrf_token %}
                    {#                    {{ form }}#}
                    {% for field in form.visible_fields %}
                        <td{% if forloop.last %} class="center-align"{% endif %}>
                            {% if forloop.first %}
                                {% for hidden in form.hidden_fields %}
                                    {{ hidden }}
                                {% endfor %}
                            {% endif %}
                            {{ field.errors.as_ul }}
                            {{ field|materializecss }}
                            {#                                    {{ field }}#}
                        </td>
                    {% endfor %}

                    {#                    {{ form.title|materializecss }}#}
                    {#                    {{ form.image|materializecss }}#}
                </div>

                <h5>{% trans "Option values" %}</h5>
                {{ formset.management_form }}
                {{ formset.non_form_errors.as_ul }}
                <table id="formset" class="highlight">
                    {% for form in formset.forms %}
                        {% if forloop.first %}
                            <thead>
                            <tr>
                                {% for field in form.visible_fields %}
                                    <th>{{ field.label|capfirst }}</th>
                                {% endfor %}
                            </tr>
                            </thead>
                        {% endif %}
                        <tr>
{#                        {{ form }}#}
                            {% for field in form.visible_fields %}
                                <td{% if forloop.last %} class="center-align"{% endif %}>
                                    {% if forloop.first %}
                                        {% for hidden in form.hidden_fields %}
                                            {{ hidden }}
                                        {% endfor %}
                                    {% endif %}
                                    {{ field.errors.as_ul }}
{#                                                                        {{ field|materializecss }}#}
                                    {{ field }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>

        <div class="row">
            <div class="col l8 right-align">
                {% if option.pk %}
                    <button type="submit" class="btn">{% trans "Update" %}</button>
                {% else %}
                    <button type="submit" class="btn">{% trans "Create" %}</button>
                {% endif %}
            </div>
        </div>
    </form>
{% endblock %}

saleor/dashboard/templates/dashboard/product/option/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}

{% block title %}{% trans "Options" %} - {{ block.super }}{% endblock %}

{% block body_class %}body-options{% endblock %}

{% block header_extra %}
    <div class="fixed-action-btn">
        <a class="btn-fab btn-floating btn-large waves-effect waves-light teal"
            href="{% url 'dashboard:product-option-add' %}" title="{% trans "Add option" %}">
            <i class="mdi-content-add"></i>
        </a>
    </div>
{% endblock %}

{% block breadcrumbs %}
    <ul class="breadcrumbs">
        <li>{% trans "Options" %}</li>
    </ul>
{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
    <div class="row">
        <div class="col s12">
            {% if options %}
                <ul class="collection list list--options">
                    {% for option in options %}
                        <li class="collection-item list-item list--options-item list-item--two-lines">
                            <a class="list-item-name" href="{% url 'dashboard:product-option-update' pk=option.pk %}">{{ option.title }}</a>
                            <p class="list-item-desc">
                                    {% for value in option.values.all %}
                                    {{ value }}{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>{% trans "No options found." %}</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

saleor/dashboard/templates/dashboard/product/option/modal_confirm_delete.html
{% load i18n %}

<form action="{% url "dashboard:product-option-delete" pk=optionSet.pk %}" method="post">
    {% csrf_token %}
    <div class="modal-content">
        <h5>{% trans "Are you sure?" %}</h5>

        <p>
            {% blocktrans %}You are about to delete an option <strong>{{ optionSet }}</strong>.{% endblocktrans %}
        </p>
    </div>

    <div class="modal-footer">
        <button type="submit" class="modal-option btn-flat blue-text">{% trans "Delete" %}</button>
        <a href="#!" class="modal-action modal-close btn-flat blue-text">{% trans "Cancel" %}</a>
    </div>
</form>